apiVersion: infrastructure.dcnlab.ssu.ac.kr/v1beta1
kind: KTCluster
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: edge01
spec:
  apiServerLoadBalancer:
    enabled: false
  controlPlaneExternalNetworkEnable: true
  identityRef:
    cloudName: openstack
    name: edge01-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: this is for control plane only
      direction: ingress
      portRangeMax: 1
      portRangeMin: 65535
      protocol: ALL
      dstip: "0.0.0.0/0"
      action: allow
      appliesTo:
      - controlplane
    - description: this is for all nodes
      direction: egress
      portRangeMax: 1
      portRangeMin: 65535
      protocol: ALL
      dstip: "0.0.0.0/0"
      action: allow
      appliesTo:
      - controlplane
      - worker
  # managedSubnets:
  # - cidr: 10.6.0.0/24
  #   dnsNameservers:
  #   - 8.8.8.8

