apiVersion: infrastructure.dcnlab.ssu.ac.kr/v1beta1
kind: KTMachineTemplate
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: edge01-control-plane
spec:
  template:
    spec:
      flavor: a12c8f89-e8f7-4f68-9c00-e376f9a1ab8d
      blockDeviceMapping:
        - id: ece8ab48-0752-4de0-bf93-f189c60946de
          bootIndex: 0
          sourceType: image
          volumeSize: 50
          destinationType: volume
      networkTier:
        - id: 7031a1e3-7435-4cd2-9087-671a995f3bbd
      sshKeyName: test1
