apiVersion: infrastructure.dcnlab.ssu.ac.kr/v1beta1
kind: KTSubjectToken
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: kt-cluster1
spec:
  subjectToken: gAAAAABofn-bglvKUqbEHhKD9_dPwR31imRUJ4g6JRxN2PIvgTWYqIn9w0PoaZ5yqCXFkLE-tSfPaunqs7w28lNN1quvYe3E5VUuooEx6NvVWni3vQ_onKr8Ey129IzIQOfERGiUtXbQvHfQFt_YHOl4ZbcD8aTCfopLcf5TvNnsdBYJ1dSI23g
  token:
    expiresAt: "2026-12-18T03:47:08.000000Z"

