apiVersion: infrastructure.dcnlab.ssu.ac.kr/v1beta1
kind: KTCluster
metadata:
  labels:
    app.kubernetes.io/name: kt-cloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: edge01
spec:
  apiServerLoadBalancer:
    enabled: false
  controlPlaneExternalNetworkEnable: true
  identityRef:
    cloudName: openstack
    name: edge01-cloud-config
  managedSecurityGroups:
    controlPlaneRules:
      direction: ingress
      startPort: 1
      endPort: 65535
      protocol: ALL
      dstip: "0.0.0.0/0"
      action: allow
    workerRules:
      direction: egress
      startPort: 1
      endPort: 65535
      protocol: ALL
      dstip: "0.0.0.0/0"
      action: allow
  # managedSubnets:
  # - cidr: 10.6.0.0/24
  #   dnsNameservers:
  #   - 8.8.8.8

